! Copyright (C) 2026 Zynum contributors
! SPDX-License-Identifier: LGPL-3.0-or-later
! Generated by tools/generate_compat_headers.zig.
! Project contact: Kaixiang Huang
! Fortran 2003+ ISO_C_BINDING module for the Zynum BLAS compatibility ABI.
module zynum_blas_fortran
  use, intrinsic :: iso_c_binding, only: &
      c_int, c_float, c_double, c_char, &
      c_float_complex, c_double_complex
  implicit none

  integer, parameter :: blasint = c_int
  integer, parameter :: blas_complex_float = c_float_complex
  integer, parameter :: blas_complex_double = c_double_complex

  ! Compatibility aliases for earlier Zynum BLAS module revisions.
  integer, parameter :: blas_int = blasint
  integer, parameter :: blas_complex_f32 = blas_complex_float
  integer, parameter :: blas_complex_f64 = blas_complex_double

  interface
    function lsame( &
        ca, cb &
    ) bind(C, name="lsame_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: ca
      character(kind=c_char), intent(in) :: cb
      integer(c_int) :: res
    end function lsame

    subroutine xerbla( &
        srname, info &
    ) bind(C, name="xerbla_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: srname
      integer(blasint), intent(in) :: info
    end subroutine xerbla

    subroutine xerbla_array( &
        srname_array, srname_len, info &
    ) bind(C, name="xerbla_array_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: srname_array(*)
      integer(blasint), intent(in) :: srname_len
      integer(blasint), intent(in) :: info
    end subroutine xerbla_array

    function scabs1( &
        z &
    ) bind(C, name="scabs1_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      complex(blas_complex_float), intent(in) :: z
      real(c_float) :: res
    end function scabs1

    function dcabs1( &
        z &
    ) bind(C, name="dcabs1_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      complex(blas_complex_double), intent(in) :: z
      real(c_double) :: res
    end function dcabs1

    subroutine sswap( &
        n, x, incx, y, incy &
    ) bind(C, name="sswap_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine sswap

    subroutine dswap( &
        n, x, incx, y, incy &
    ) bind(C, name="dswap_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine dswap

    subroutine cswap( &
        n, x, incx, y, incy &
    ) bind(C, name="cswap_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine cswap

    subroutine zswap( &
        n, x, incx, y, incy &
    ) bind(C, name="zswap_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zswap

    subroutine scopy( &
        n, x, incx, y, incy &
    ) bind(C, name="scopy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine scopy

    subroutine dcopy( &
        n, x, incx, y, incy &
    ) bind(C, name="dcopy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine dcopy

    subroutine ccopy( &
        n, x, incx, y, incy &
    ) bind(C, name="ccopy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine ccopy

    subroutine zcopy( &
        n, x, incx, y, incy &
    ) bind(C, name="zcopy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zcopy

    subroutine saxpy( &
        n, alpha, x, incx, y, incy &
    ) bind(C, name="saxpy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine saxpy

    subroutine daxpy( &
        n, alpha, x, incx, y, incy &
    ) bind(C, name="daxpy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine daxpy

    subroutine caxpy( &
        n, alpha, x, incx, y, incy &
    ) bind(C, name="caxpy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine caxpy

    subroutine zaxpy( &
        n, alpha, x, incx, y, incy &
    ) bind(C, name="zaxpy_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zaxpy

    subroutine saxpby( &
        n, alpha, x, incx, beta, y, &
        incy &
    ) bind(C, name="saxpby_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine saxpby

    subroutine daxpby( &
        n, alpha, x, incx, beta, y, &
        incy &
    ) bind(C, name="daxpby_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine daxpby

    subroutine caxpby( &
        n, alpha, x, incx, beta, y, &
        incy &
    ) bind(C, name="caxpby_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine caxpby

    subroutine zaxpby( &
        n, alpha, x, incx, beta, y, &
        incy &
    ) bind(C, name="zaxpby_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zaxpby

    function sdot( &
        n, x, incx, y, incy &
    ) bind(C, name="sdot_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float) :: res
    end function sdot

    function ddot( &
        n, x, incx, y, incy &
    ) bind(C, name="ddot_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double) :: res
    end function ddot

    function cdotu( &
        n, x, incx, y, incy &
    ) bind(C, name="cdotu_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float) :: res
    end function cdotu

    function zdotu( &
        n, x, incx, y, incy &
    ) bind(C, name="zdotu_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double) :: res
    end function zdotu

    function cdotc( &
        n, x, incx, y, incy &
    ) bind(C, name="cdotc_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float) :: res
    end function cdotc

    function zdotc( &
        n, x, incx, y, incy &
    ) bind(C, name="zdotc_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double) :: res
    end function zdotc

    subroutine cdotu_sub( &
        n, x, incx, y, incy, out &
    ) bind(C, name="cdotu_sub_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float), intent(inout) :: out
    end subroutine cdotu_sub

    subroutine zdotu_sub( &
        n, x, incx, y, incy, out &
    ) bind(C, name="zdotu_sub_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double), intent(inout) :: out
    end subroutine zdotu_sub

    subroutine cdotc_sub( &
        n, x, incx, y, incy, out &
    ) bind(C, name="cdotc_sub_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float), intent(inout) :: out
    end subroutine cdotc_sub

    subroutine zdotc_sub( &
        n, x, incx, y, incy, out &
    ) bind(C, name="zdotc_sub_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double), intent(inout) :: out
    end subroutine zdotc_sub

    function sdsdot( &
        n, sb, x, incx, y, incy &
    ) bind(C, name="sdsdot_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: sb
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float) :: res
    end function sdsdot

    function dsdot( &
        n, x, incx, y, incy &
    ) bind(C, name="dsdot_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double) :: res
    end function dsdot

    function snrm2( &
        n, x, incx &
    ) bind(C, name="snrm2_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float) :: res
    end function snrm2

    function dnrm2( &
        n, x, incx &
    ) bind(C, name="dnrm2_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double) :: res
    end function dnrm2

    function scnrm2( &
        n, x, incx &
    ) bind(C, name="scnrm2_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float) :: res
    end function scnrm2

    function dznrm2( &
        n, x, incx &
    ) bind(C, name="dznrm2_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double) :: res
    end function dznrm2

    function sasum( &
        n, x, incx &
    ) bind(C, name="sasum_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float) :: res
    end function sasum

    function dasum( &
        n, x, incx &
    ) bind(C, name="dasum_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double) :: res
    end function dasum

    function scasum( &
        n, x, incx &
    ) bind(C, name="scasum_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float) :: res
    end function scasum

    function dzasum( &
        n, x, incx &
    ) bind(C, name="dzasum_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double) :: res
    end function dzasum

    function isamax( &
        n, x, incx &
    ) bind(C, name="isamax_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      integer(blasint) :: res
    end function isamax

    function idamax( &
        n, x, incx &
    ) bind(C, name="idamax_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      integer(blasint) :: res
    end function idamax

    function icamax( &
        n, x, incx &
    ) bind(C, name="icamax_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      integer(blasint) :: res
    end function icamax

    function izamax( &
        n, x, incx &
    ) bind(C, name="izamax_") result(res)
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      integer(blasint) :: res
    end function izamax

    subroutine srotg( &
        a, b, c, s &
    ) bind(C, name="srotg_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      real(c_float), intent(inout) :: a
      real(c_float), intent(inout) :: b
      real(c_float), intent(inout) :: c
      real(c_float), intent(inout) :: s
    end subroutine srotg

    subroutine drotg( &
        a, b, c, s &
    ) bind(C, name="drotg_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      real(c_double), intent(inout) :: a
      real(c_double), intent(inout) :: b
      real(c_double), intent(inout) :: c
      real(c_double), intent(inout) :: s
    end subroutine drotg

    subroutine crotg( &
        a, b, c, s &
    ) bind(C, name="crotg_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      complex(blas_complex_float), intent(inout) :: a
      complex(blas_complex_float), intent(inout) :: b
      real(c_float), intent(inout) :: c
      complex(blas_complex_float), intent(inout) :: s
    end subroutine crotg

    subroutine zrotg( &
        a, b, c, s &
    ) bind(C, name="zrotg_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      complex(blas_complex_double), intent(inout) :: a
      complex(blas_complex_double), intent(inout) :: b
      real(c_double), intent(inout) :: c
      complex(blas_complex_double), intent(inout) :: s
    end subroutine zrotg

    subroutine srot( &
        n, x, incx, y, incy, c, &
        s &
    ) bind(C, name="srot_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float), intent(in) :: c
      real(c_float), intent(in) :: s
    end subroutine srot

    subroutine drot( &
        n, x, incx, y, incy, c, &
        s &
    ) bind(C, name="drot_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double), intent(in) :: c
      real(c_double), intent(in) :: s
    end subroutine drot

    subroutine csrot( &
        n, x, incx, y, incy, c, &
        s &
    ) bind(C, name="csrot_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float), intent(in) :: c
      real(c_float), intent(in) :: s
    end subroutine csrot

    subroutine zdrot( &
        n, x, incx, y, incy, c, &
        s &
    ) bind(C, name="zdrot_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double), intent(in) :: c
      real(c_double), intent(in) :: s
    end subroutine zdrot

    subroutine srotm( &
        n, x, incx, y, incy, param &
    ) bind(C, name="srotm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float), intent(in) :: param(*)
    end subroutine srotm

    subroutine drotm( &
        n, x, incx, y, incy, param &
    ) bind(C, name="drotm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double), intent(in) :: param(*)
    end subroutine drotm

    subroutine srotmg( &
        d1, d2, x1, y1, param &
    ) bind(C, name="srotmg_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      real(c_float), intent(inout) :: d1
      real(c_float), intent(inout) :: d2
      real(c_float), intent(inout) :: x1
      real(c_float), intent(in) :: y1
      real(c_float), intent(inout) :: param(*)
    end subroutine srotmg

    subroutine drotmg( &
        d1, d2, x1, y1, param &
    ) bind(C, name="drotmg_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      real(c_double), intent(inout) :: d1
      real(c_double), intent(inout) :: d2
      real(c_double), intent(inout) :: x1
      real(c_double), intent(in) :: y1
      real(c_double), intent(inout) :: param(*)
    end subroutine drotmg

    subroutine sscal( &
        n, alpha, x, incx &
    ) bind(C, name="sscal_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine sscal

    subroutine dscal( &
        n, alpha, x, incx &
    ) bind(C, name="dscal_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine dscal

    subroutine cscal( &
        n, alpha, x, incx &
    ) bind(C, name="cscal_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine cscal

    subroutine zscal( &
        n, alpha, x, incx &
    ) bind(C, name="zscal_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine zscal

    subroutine csscal( &
        n, alpha, x, incx &
    ) bind(C, name="csscal_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine csscal

    subroutine zdscal( &
        n, alpha, x, incx &
    ) bind(C, name="zdscal_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine zdscal

    subroutine sgemv( &
        t, m, n, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="sgemv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine sgemv

    subroutine dgemv( &
        t, m, n, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="dgemv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine dgemv

    subroutine cgemv( &
        t, m, n, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="cgemv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine cgemv

    subroutine zgemv( &
        t, m, n, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="zgemv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zgemv

    subroutine sgbmv( &
        t, m, n, kl, ku, alpha, &
        a, lda, x, incx, beta, y, &
        incy &
    ) bind(C, name="sgbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: kl
      integer(blasint), intent(in) :: ku
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine sgbmv

    subroutine dgbmv( &
        t, m, n, kl, ku, alpha, &
        a, lda, x, incx, beta, y, &
        incy &
    ) bind(C, name="dgbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: kl
      integer(blasint), intent(in) :: ku
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine dgbmv

    subroutine cgbmv( &
        t, m, n, kl, ku, alpha, &
        a, lda, x, incx, beta, y, &
        incy &
    ) bind(C, name="cgbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: kl
      integer(blasint), intent(in) :: ku
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine cgbmv

    subroutine zgbmv( &
        t, m, n, kl, ku, alpha, &
        a, lda, x, incx, beta, y, &
        incy &
    ) bind(C, name="zgbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: kl
      integer(blasint), intent(in) :: ku
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zgbmv

    subroutine ssymv( &
        u, n, alpha, a, lda, x, &
        incx, beta, y, incy &
    ) bind(C, name="ssymv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine ssymv

    subroutine dsymv( &
        u, n, alpha, a, lda, x, &
        incx, beta, y, incy &
    ) bind(C, name="dsymv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine dsymv

    subroutine chemv( &
        u, n, alpha, a, lda, x, &
        incx, beta, y, incy &
    ) bind(C, name="chemv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine chemv

    subroutine zhemv( &
        u, n, alpha, a, lda, x, &
        incx, beta, y, incy &
    ) bind(C, name="zhemv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zhemv

    subroutine ssbmv( &
        u, n, k, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="ssbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine ssbmv

    subroutine dsbmv( &
        u, n, k, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="dsbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine dsbmv

    subroutine chbmv( &
        u, n, k, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="chbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine chbmv

    subroutine zhbmv( &
        u, n, k, alpha, a, lda, &
        x, incx, beta, y, incy &
    ) bind(C, name="zhbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zhbmv

    subroutine sspmv( &
        u, n, alpha, ap, x, incx, &
        beta, y, incy &
    ) bind(C, name="sspmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: ap(*)
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine sspmv

    subroutine dspmv( &
        u, n, alpha, ap, x, incx, &
        beta, y, incy &
    ) bind(C, name="dspmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: ap(*)
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine dspmv

    subroutine chpmv( &
        u, n, alpha, ap, x, incx, &
        beta, y, incy &
    ) bind(C, name="chpmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: ap(*)
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine chpmv

    subroutine zhpmv( &
        u, n, alpha, ap, x, incx, &
        beta, y, incy &
    ) bind(C, name="zhpmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: ap(*)
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: y(*)
      integer(blasint), intent(in) :: incy
    end subroutine zhpmv

    subroutine strmv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="strmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine strmv

    subroutine dtrmv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="dtrmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine dtrmv

    subroutine ctrmv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="ctrmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ctrmv

    subroutine ztrmv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="ztrmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ztrmv

    subroutine stbmv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="stbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine stbmv

    subroutine dtbmv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="dtbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine dtbmv

    subroutine ctbmv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="ctbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ctbmv

    subroutine ztbmv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="ztbmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ztbmv

    subroutine stpmv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="stpmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: ap(*)
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine stpmv

    subroutine dtpmv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="dtpmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: ap(*)
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine dtpmv

    subroutine ctpmv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="ctpmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: ap(*)
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ctpmv

    subroutine ztpmv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="ztpmv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: ap(*)
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ztpmv

    subroutine strsv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="strsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine strsv

    subroutine dtrsv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="dtrsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine dtrsv

    subroutine ctrsv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="ctrsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ctrsv

    subroutine ztrsv( &
        u, t, d, n, a, lda, &
        x, incx &
    ) bind(C, name="ztrsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ztrsv

    subroutine stbsv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="stbsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine stbsv

    subroutine dtbsv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="dtbsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine dtbsv

    subroutine ctbsv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="ctbsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ctbsv

    subroutine ztbsv( &
        u, t, d, n, k, a, &
        lda, x, incx &
    ) bind(C, name="ztbsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ztbsv

    subroutine stpsv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="stpsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: ap(*)
      real(c_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine stpsv

    subroutine dtpsv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="dtpsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: ap(*)
      real(c_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine dtpsv

    subroutine ctpsv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="ctpsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: ap(*)
      complex(blas_complex_float), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ctpsv

    subroutine ztpsv( &
        u, t, d, n, ap, x, &
        incx &
    ) bind(C, name="ztpsv_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: ap(*)
      complex(blas_complex_double), intent(inout) :: x(*)
      integer(blasint), intent(in) :: incx
    end subroutine ztpsv

    subroutine sger( &
        m, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="sger_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine sger

    subroutine dger( &
        m, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="dger_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine dger

    subroutine cgeru( &
        m, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="cgeru_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine cgeru

    subroutine zgeru( &
        m, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="zgeru_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine zgeru

    subroutine cgerc( &
        m, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="cgerc_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine cgerc

    subroutine zgerc( &
        m, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="zgerc_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine zgerc

    subroutine ssyr( &
        u, n, alpha, x, incx, a, &
        lda &
    ) bind(C, name="ssyr_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine ssyr

    subroutine dsyr( &
        u, n, alpha, x, incx, a, &
        lda &
    ) bind(C, name="dsyr_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine dsyr

    subroutine cher( &
        u, n, alpha, x, incx, a, &
        lda &
    ) bind(C, name="cher_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine cher

    subroutine zher( &
        u, n, alpha, x, incx, a, &
        lda &
    ) bind(C, name="zher_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine zher

    subroutine sspr( &
        u, n, alpha, x, incx, ap &
    ) bind(C, name="sspr_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(inout) :: ap(*)
    end subroutine sspr

    subroutine dspr( &
        u, n, alpha, x, incx, ap &
    ) bind(C, name="dspr_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(inout) :: ap(*)
    end subroutine dspr

    subroutine chpr( &
        u, n, alpha, x, incx, ap &
    ) bind(C, name="chpr_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(inout) :: ap(*)
    end subroutine chpr

    subroutine zhpr( &
        u, n, alpha, x, incx, ap &
    ) bind(C, name="zhpr_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(inout) :: ap(*)
    end subroutine zhpr

    subroutine ssyr2( &
        u, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="ssyr2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine ssyr2

    subroutine dsyr2( &
        u, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="dsyr2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine dsyr2

    subroutine cher2( &
        u, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="cher2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine cher2

    subroutine zher2( &
        u, n, alpha, x, incx, y, &
        incy, a, lda &
    ) bind(C, name="zher2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double), intent(inout) :: a(*)
      integer(blasint), intent(in) :: lda
    end subroutine zher2

    subroutine sspr2( &
        u, n, alpha, x, incx, y, &
        incy, ap &
    ) bind(C, name="sspr2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_float), intent(inout) :: ap(*)
    end subroutine sspr2

    subroutine dspr2( &
        u, n, alpha, x, incx, y, &
        incy, ap &
    ) bind(C, name="dspr2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      real(c_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      real(c_double), intent(inout) :: ap(*)
    end subroutine dspr2

    subroutine chpr2( &
        u, n, alpha, x, incx, y, &
        incy, ap &
    ) bind(C, name="chpr2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_float), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_float), intent(inout) :: ap(*)
    end subroutine chpr2

    subroutine zhpr2( &
        u, n, alpha, x, incx, y, &
        incy, ap &
    ) bind(C, name="zhpr2_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: x(*)
      integer(blasint), intent(in) :: incx
      complex(blas_complex_double), intent(in) :: y(*)
      integer(blasint), intent(in) :: incy
      complex(blas_complex_double), intent(inout) :: ap(*)
    end subroutine zhpr2

    subroutine sgemm( &
        ta, tb, m, n, k, alpha, &
        a, lda, b, ldb, beta, c, &
        ldc &
    ) bind(C, name="sgemm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: ta
      character(kind=c_char), intent(in) :: tb
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine sgemm

    subroutine dgemm( &
        ta, tb, m, n, k, alpha, &
        a, lda, b, ldb, beta, c, &
        ldc &
    ) bind(C, name="dgemm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: ta
      character(kind=c_char), intent(in) :: tb
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine dgemm

    subroutine cgemm( &
        ta, tb, m, n, k, alpha, &
        a, lda, b, ldb, beta, c, &
        ldc &
    ) bind(C, name="cgemm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: ta
      character(kind=c_char), intent(in) :: tb
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine cgemm

    subroutine zgemm( &
        ta, tb, m, n, k, alpha, &
        a, lda, b, ldb, beta, c, &
        ldc &
    ) bind(C, name="zgemm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: ta
      character(kind=c_char), intent(in) :: tb
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine zgemm

    subroutine ssymm( &
        side, u, m, n, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="ssymm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine ssymm

    subroutine dsymm( &
        side, u, m, n, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="dsymm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine dsymm

    subroutine csymm( &
        side, u, m, n, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="csymm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine csymm

    subroutine zsymm( &
        side, u, m, n, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="zsymm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine zsymm

    subroutine chemm( &
        side, u, m, n, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="chemm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine chemm

    subroutine zhemm( &
        side, u, m, n, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="zhemm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine zhemm

    subroutine ssyrk( &
        u, t, n, k, alpha, a, &
        lda, beta, c, ldc &
    ) bind(C, name="ssyrk_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine ssyrk

    subroutine dsyrk( &
        u, t, n, k, alpha, a, &
        lda, beta, c, ldc &
    ) bind(C, name="dsyrk_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine dsyrk

    subroutine csyrk( &
        u, t, n, k, alpha, a, &
        lda, beta, c, ldc &
    ) bind(C, name="csyrk_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine csyrk

    subroutine zsyrk( &
        u, t, n, k, alpha, a, &
        lda, beta, c, ldc &
    ) bind(C, name="zsyrk_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine zsyrk

    subroutine cherk( &
        u, t, n, k, alpha, a, &
        lda, beta, c, ldc &
    ) bind(C, name="cherk_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine cherk

    subroutine zherk( &
        u, t, n, k, alpha, a, &
        lda, beta, c, ldc &
    ) bind(C, name="zherk_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine zherk

    subroutine ssyr2k( &
        u, t, n, k, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="ssyr2k_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_float), intent(in) :: beta
      real(c_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine ssyr2k

    subroutine dsyr2k( &
        u, t, n, k, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="dsyr2k_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_double), intent(in) :: beta
      real(c_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine dsyr2k

    subroutine csyr2k( &
        u, t, n, k, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="csyr2k_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine csyr2k

    subroutine zsyr2k( &
        u, t, n, k, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="zsyr2k_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      complex(blas_complex_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine zsyr2k

    subroutine cher2k( &
        u, t, n, k, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="cher2k_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_float), intent(in) :: beta
      complex(blas_complex_float), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine cher2k

    subroutine zher2k( &
        u, t, n, k, alpha, a, &
        lda, b, ldb, beta, c, ldc &
    ) bind(C, name="zher2k_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      integer(blasint), intent(in) :: n
      integer(blasint), intent(in) :: k
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(in) :: b(*)
      integer(blasint), intent(in) :: ldb
      real(c_double), intent(in) :: beta
      complex(blas_complex_double), intent(inout) :: c(*)
      integer(blasint), intent(in) :: ldc
    end subroutine zher2k

    subroutine strmm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="strmm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine strmm

    subroutine dtrmm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="dtrmm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine dtrmm

    subroutine ctrmm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="ctrmm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine ctrmm

    subroutine ztrmm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="ztrmm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine ztrmm

    subroutine strsm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="strsm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_float), intent(in) :: alpha
      real(c_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_float), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine strsm

    subroutine dtrsm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="dtrsm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      real(c_double), intent(in) :: alpha
      real(c_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      real(c_double), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine dtrsm

    subroutine ctrsm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="ctrsm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_float), intent(in) :: alpha
      complex(blas_complex_float), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_float), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine ctrsm

    subroutine ztrsm( &
        side, u, t, d, m, n, &
        alpha, a, lda, b, ldb &
    ) bind(C, name="ztrsm_")
      import :: c_int, c_float, c_double, c_char
      import :: blasint, blas_complex_float, blas_complex_double
      character(kind=c_char), intent(in) :: side
      character(kind=c_char), intent(in) :: u
      character(kind=c_char), intent(in) :: t
      character(kind=c_char), intent(in) :: d
      integer(blasint), intent(in) :: m
      integer(blasint), intent(in) :: n
      complex(blas_complex_double), intent(in) :: alpha
      complex(blas_complex_double), intent(in) :: a(*)
      integer(blasint), intent(in) :: lda
      complex(blas_complex_double), intent(inout) :: b(*)
      integer(blasint), intent(in) :: ldb
    end subroutine ztrsm
  end interface
end module zynum_blas_fortran
