/*
 * Copyright (C) 2026 Zynum contributors
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Generated by tools/generate_compat_headers.zig.
 * Project contact: Kaixiang Huang
 */
#ifndef ZYNUM_BLAS_BLAS_H
#define ZYNUM_BLAS_BLAS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef ZYNUM_BLAS_TYPES_DEFINED
#define ZYNUM_BLAS_TYPES_DEFINED
typedef int32_t zynum_blas_int;
typedef struct {
    float real;
    float imag;
} zynum_blas_complex_float;
typedef struct {
    double real;
    double imag;
} zynum_blas_complex_double;
typedef zynum_blas_complex_float zynum_blas_complexF32;
typedef zynum_blas_complex_double zynum_blas_complexF64;
#endif

int lsame_(const char *ca, const char *cb);
void xerbla_(const char *srname, const zynum_blas_int *info);
void xerbla_array_(const char *srname_array, const zynum_blas_int *srname_len, const zynum_blas_int *info);
float scabs1_(const zynum_blas_complex_float *z);
double dcabs1_(const zynum_blas_complex_double *z);
void sswap_(const zynum_blas_int *n, float *x, const zynum_blas_int *incx, float *y, const zynum_blas_int *incy);
void dswap_(const zynum_blas_int *n, double *x, const zynum_blas_int *incx, double *y, const zynum_blas_int *incy);
void cswap_(const zynum_blas_int *n, zynum_blas_complex_float *x, const zynum_blas_int *incx, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zswap_(const zynum_blas_int *n, zynum_blas_complex_double *x, const zynum_blas_int *incx, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void scopy_(const zynum_blas_int *n, const float *x, const zynum_blas_int *incx, float *y, const zynum_blas_int *incy);
void dcopy_(const zynum_blas_int *n, const double *x, const zynum_blas_int *incx, double *y, const zynum_blas_int *incy);
void ccopy_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zcopy_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void saxpy_(const zynum_blas_int *n, const float *alpha, const float *x, const zynum_blas_int *incx, float *y, const zynum_blas_int *incy);
void daxpy_(const zynum_blas_int *n, const double *alpha, const double *x, const zynum_blas_int *incx, double *y, const zynum_blas_int *incy);
void caxpy_(const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zaxpy_(const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void saxpby_(const zynum_blas_int *n, const float *alpha, const float *x, const zynum_blas_int *incx, const float *beta, float *y, const zynum_blas_int *incy);
void daxpby_(const zynum_blas_int *n, const double *alpha, const double *x, const zynum_blas_int *incx, const double *beta, double *y, const zynum_blas_int *incy);
void caxpby_(const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *beta, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zaxpby_(const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *beta, zynum_blas_complex_double *y, const zynum_blas_int *incy);
float sdot_(const zynum_blas_int *n, const float *x, const zynum_blas_int *incx, const float *y, const zynum_blas_int *incy);
double ddot_(const zynum_blas_int *n, const double *x, const zynum_blas_int *incx, const double *y, const zynum_blas_int *incy);
zynum_blas_complex_float cdotu_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy);
zynum_blas_complex_double zdotu_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy);
zynum_blas_complex_float cdotc_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy);
zynum_blas_complex_double zdotc_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy);
void cdotu_sub_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy, zynum_blas_complex_float *out);
void zdotu_sub_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy, zynum_blas_complex_double *out);
void cdotc_sub_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy, zynum_blas_complex_float *out);
void zdotc_sub_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy, zynum_blas_complex_double *out);
float sdsdot_(const zynum_blas_int *n, const float *sb, const float *x, const zynum_blas_int *incx, const float *y, const zynum_blas_int *incy);
double dsdot_(const zynum_blas_int *n, const float *x, const zynum_blas_int *incx, const float *y, const zynum_blas_int *incy);
float snrm2_(const zynum_blas_int *n, const float *x, const zynum_blas_int *incx);
double dnrm2_(const zynum_blas_int *n, const double *x, const zynum_blas_int *incx);
float scnrm2_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx);
double dznrm2_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx);
float sasum_(const zynum_blas_int *n, const float *x, const zynum_blas_int *incx);
double dasum_(const zynum_blas_int *n, const double *x, const zynum_blas_int *incx);
float scasum_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx);
double dzasum_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx);
zynum_blas_int isamax_(const zynum_blas_int *n, const float *x, const zynum_blas_int *incx);
zynum_blas_int idamax_(const zynum_blas_int *n, const double *x, const zynum_blas_int *incx);
zynum_blas_int icamax_(const zynum_blas_int *n, const zynum_blas_complex_float *x, const zynum_blas_int *incx);
zynum_blas_int izamax_(const zynum_blas_int *n, const zynum_blas_complex_double *x, const zynum_blas_int *incx);
void srotg_(float *a, float *b, float *c, float *s);
void drotg_(double *a, double *b, double *c, double *s);
void crotg_(zynum_blas_complex_float *a, zynum_blas_complex_float *b, float *c, zynum_blas_complex_float *s);
void zrotg_(zynum_blas_complex_double *a, zynum_blas_complex_double *b, double *c, zynum_blas_complex_double *s);
void srot_(const zynum_blas_int *n, float *x, const zynum_blas_int *incx, float *y, const zynum_blas_int *incy, const float *c, const float *s);
void drot_(const zynum_blas_int *n, double *x, const zynum_blas_int *incx, double *y, const zynum_blas_int *incy, const double *c, const double *s);
void csrot_(const zynum_blas_int *n, zynum_blas_complex_float *x, const zynum_blas_int *incx, zynum_blas_complex_float *y, const zynum_blas_int *incy, const float *c, const float *s);
void zdrot_(const zynum_blas_int *n, zynum_blas_complex_double *x, const zynum_blas_int *incx, zynum_blas_complex_double *y, const zynum_blas_int *incy, const double *c, const double *s);
void srotm_(const zynum_blas_int *n, float *x, const zynum_blas_int *incx, float *y, const zynum_blas_int *incy, const float *param);
void drotm_(const zynum_blas_int *n, double *x, const zynum_blas_int *incx, double *y, const zynum_blas_int *incy, const double *param);
void srotmg_(float *d1, float *d2, float *x1, const float *y1, float *param);
void drotmg_(double *d1, double *d2, double *x1, const double *y1, double *param);
void sscal_(const zynum_blas_int *n, const float *alpha, float *x, const zynum_blas_int *incx);
void dscal_(const zynum_blas_int *n, const double *alpha, double *x, const zynum_blas_int *incx);
void cscal_(const zynum_blas_int *n, const zynum_blas_complex_float *alpha, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void zscal_(const zynum_blas_int *n, const zynum_blas_complex_double *alpha, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void csscal_(const zynum_blas_int *n, const float *alpha, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void zdscal_(const zynum_blas_int *n, const double *alpha, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void sgemv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const float *alpha, const float *a, const zynum_blas_int *lda, const float *x, const zynum_blas_int *incx, const float *beta, float *y, const zynum_blas_int *incy);
void dgemv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const double *alpha, const double *a, const zynum_blas_int *lda, const double *x, const zynum_blas_int *incx, const double *beta, double *y, const zynum_blas_int *incy);
void cgemv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *beta, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zgemv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *beta, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void sgbmv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *kl, const zynum_blas_int *ku, const float *alpha, const float *a, const zynum_blas_int *lda, const float *x, const zynum_blas_int *incx, const float *beta, float *y, const zynum_blas_int *incy);
void dgbmv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *kl, const zynum_blas_int *ku, const double *alpha, const double *a, const zynum_blas_int *lda, const double *x, const zynum_blas_int *incx, const double *beta, double *y, const zynum_blas_int *incy);
void cgbmv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *kl, const zynum_blas_int *ku, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *beta, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zgbmv_(const char *t, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *kl, const zynum_blas_int *ku, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *beta, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void ssymv_(const char *u, const zynum_blas_int *n, const float *alpha, const float *a, const zynum_blas_int *lda, const float *x, const zynum_blas_int *incx, const float *beta, float *y, const zynum_blas_int *incy);
void dsymv_(const char *u, const zynum_blas_int *n, const double *alpha, const double *a, const zynum_blas_int *lda, const double *x, const zynum_blas_int *incx, const double *beta, double *y, const zynum_blas_int *incy);
void chemv_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *beta, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zhemv_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *beta, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void ssbmv_(const char *u, const zynum_blas_int *n, const zynum_blas_int *k, const float *alpha, const float *a, const zynum_blas_int *lda, const float *x, const zynum_blas_int *incx, const float *beta, float *y, const zynum_blas_int *incy);
void dsbmv_(const char *u, const zynum_blas_int *n, const zynum_blas_int *k, const double *alpha, const double *a, const zynum_blas_int *lda, const double *x, const zynum_blas_int *incx, const double *beta, double *y, const zynum_blas_int *incy);
void chbmv_(const char *u, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *beta, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zhbmv_(const char *u, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *beta, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void sspmv_(const char *u, const zynum_blas_int *n, const float *alpha, const float *ap, const float *x, const zynum_blas_int *incx, const float *beta, float *y, const zynum_blas_int *incy);
void dspmv_(const char *u, const zynum_blas_int *n, const double *alpha, const double *ap, const double *x, const zynum_blas_int *incx, const double *beta, double *y, const zynum_blas_int *incy);
void chpmv_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *ap, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *beta, zynum_blas_complex_float *y, const zynum_blas_int *incy);
void zhpmv_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *ap, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *beta, zynum_blas_complex_double *y, const zynum_blas_int *incy);
void strmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const float *a, const zynum_blas_int *lda, float *x, const zynum_blas_int *incx);
void dtrmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const double *a, const zynum_blas_int *lda, double *x, const zynum_blas_int *incx);
void ctrmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_float *a, const zynum_blas_int *lda, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void ztrmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_double *a, const zynum_blas_int *lda, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void stbmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const float *a, const zynum_blas_int *lda, float *x, const zynum_blas_int *incx);
void dtbmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const double *a, const zynum_blas_int *lda, double *x, const zynum_blas_int *incx);
void ctbmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_float *a, const zynum_blas_int *lda, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void ztbmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_double *a, const zynum_blas_int *lda, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void stpmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const float *ap, float *x, const zynum_blas_int *incx);
void dtpmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const double *ap, double *x, const zynum_blas_int *incx);
void ctpmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_float *ap, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void ztpmv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_double *ap, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void strsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const float *a, const zynum_blas_int *lda, float *x, const zynum_blas_int *incx);
void dtrsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const double *a, const zynum_blas_int *lda, double *x, const zynum_blas_int *incx);
void ctrsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_float *a, const zynum_blas_int *lda, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void ztrsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_double *a, const zynum_blas_int *lda, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void stbsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const float *a, const zynum_blas_int *lda, float *x, const zynum_blas_int *incx);
void dtbsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const double *a, const zynum_blas_int *lda, double *x, const zynum_blas_int *incx);
void ctbsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_float *a, const zynum_blas_int *lda, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void ztbsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_double *a, const zynum_blas_int *lda, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void stpsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const float *ap, float *x, const zynum_blas_int *incx);
void dtpsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const double *ap, double *x, const zynum_blas_int *incx);
void ctpsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_float *ap, zynum_blas_complex_float *x, const zynum_blas_int *incx);
void ztpsv_(const char *u, const char *t, const char *d, const zynum_blas_int *n, const zynum_blas_complex_double *ap, zynum_blas_complex_double *x, const zynum_blas_int *incx);
void sger_(const zynum_blas_int *m, const zynum_blas_int *n, const float *alpha, const float *x, const zynum_blas_int *incx, const float *y, const zynum_blas_int *incy, float *a, const zynum_blas_int *lda);
void dger_(const zynum_blas_int *m, const zynum_blas_int *n, const double *alpha, const double *x, const zynum_blas_int *incx, const double *y, const zynum_blas_int *incy, double *a, const zynum_blas_int *lda);
void cgeru_(const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy, zynum_blas_complex_float *a, const zynum_blas_int *lda);
void zgeru_(const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy, zynum_blas_complex_double *a, const zynum_blas_int *lda);
void cgerc_(const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy, zynum_blas_complex_float *a, const zynum_blas_int *lda);
void zgerc_(const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy, zynum_blas_complex_double *a, const zynum_blas_int *lda);
void ssyr_(const char *u, const zynum_blas_int *n, const float *alpha, const float *x, const zynum_blas_int *incx, float *a, const zynum_blas_int *lda);
void dsyr_(const char *u, const zynum_blas_int *n, const double *alpha, const double *x, const zynum_blas_int *incx, double *a, const zynum_blas_int *lda);
void cher_(const char *u, const zynum_blas_int *n, const float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, zynum_blas_complex_float *a, const zynum_blas_int *lda);
void zher_(const char *u, const zynum_blas_int *n, const double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, zynum_blas_complex_double *a, const zynum_blas_int *lda);
void sspr_(const char *u, const zynum_blas_int *n, const float *alpha, const float *x, const zynum_blas_int *incx, float *ap);
void dspr_(const char *u, const zynum_blas_int *n, const double *alpha, const double *x, const zynum_blas_int *incx, double *ap);
void chpr_(const char *u, const zynum_blas_int *n, const float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, zynum_blas_complex_float *ap);
void zhpr_(const char *u, const zynum_blas_int *n, const double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, zynum_blas_complex_double *ap);
void ssyr2_(const char *u, const zynum_blas_int *n, const float *alpha, const float *x, const zynum_blas_int *incx, const float *y, const zynum_blas_int *incy, float *a, const zynum_blas_int *lda);
void dsyr2_(const char *u, const zynum_blas_int *n, const double *alpha, const double *x, const zynum_blas_int *incx, const double *y, const zynum_blas_int *incy, double *a, const zynum_blas_int *lda);
void cher2_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy, zynum_blas_complex_float *a, const zynum_blas_int *lda);
void zher2_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy, zynum_blas_complex_double *a, const zynum_blas_int *lda);
void sspr2_(const char *u, const zynum_blas_int *n, const float *alpha, const float *x, const zynum_blas_int *incx, const float *y, const zynum_blas_int *incy, float *ap);
void dspr2_(const char *u, const zynum_blas_int *n, const double *alpha, const double *x, const zynum_blas_int *incx, const double *y, const zynum_blas_int *incy, double *ap);
void chpr2_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *x, const zynum_blas_int *incx, const zynum_blas_complex_float *y, const zynum_blas_int *incy, zynum_blas_complex_float *ap);
void zhpr2_(const char *u, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *x, const zynum_blas_int *incx, const zynum_blas_complex_double *y, const zynum_blas_int *incy, zynum_blas_complex_double *ap);
void sgemm_(const char *ta, const char *tb, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *k, const float *alpha, const float *a, const zynum_blas_int *lda, const float *b, const zynum_blas_int *ldb, const float *beta, float *c, const zynum_blas_int *ldc);
void dgemm_(const char *ta, const char *tb, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *k, const double *alpha, const double *a, const zynum_blas_int *lda, const double *b, const zynum_blas_int *ldb, const double *beta, double *c, const zynum_blas_int *ldc);
void cgemm_(const char *ta, const char *tb, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *b, const zynum_blas_int *ldb, const zynum_blas_complex_float *beta, zynum_blas_complex_float *c, const zynum_blas_int *ldc);
void zgemm_(const char *ta, const char *tb, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *b, const zynum_blas_int *ldb, const zynum_blas_complex_double *beta, zynum_blas_complex_double *c, const zynum_blas_int *ldc);
void ssymm_(const char *side, const char *u, const zynum_blas_int *m, const zynum_blas_int *n, const float *alpha, const float *a, const zynum_blas_int *lda, const float *b, const zynum_blas_int *ldb, const float *beta, float *c, const zynum_blas_int *ldc);
void dsymm_(const char *side, const char *u, const zynum_blas_int *m, const zynum_blas_int *n, const double *alpha, const double *a, const zynum_blas_int *lda, const double *b, const zynum_blas_int *ldb, const double *beta, double *c, const zynum_blas_int *ldc);
void csymm_(const char *side, const char *u, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *b, const zynum_blas_int *ldb, const zynum_blas_complex_float *beta, zynum_blas_complex_float *c, const zynum_blas_int *ldc);
void zsymm_(const char *side, const char *u, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *b, const zynum_blas_int *ldb, const zynum_blas_complex_double *beta, zynum_blas_complex_double *c, const zynum_blas_int *ldc);
void chemm_(const char *side, const char *u, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *b, const zynum_blas_int *ldb, const zynum_blas_complex_float *beta, zynum_blas_complex_float *c, const zynum_blas_int *ldc);
void zhemm_(const char *side, const char *u, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *b, const zynum_blas_int *ldb, const zynum_blas_complex_double *beta, zynum_blas_complex_double *c, const zynum_blas_int *ldc);
void ssyrk_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const float *alpha, const float *a, const zynum_blas_int *lda, const float *beta, float *c, const zynum_blas_int *ldc);
void dsyrk_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const double *alpha, const double *a, const zynum_blas_int *lda, const double *beta, double *c, const zynum_blas_int *ldc);
void csyrk_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *beta, zynum_blas_complex_float *c, const zynum_blas_int *ldc);
void zsyrk_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *beta, zynum_blas_complex_double *c, const zynum_blas_int *ldc);
void cherk_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const float *beta, zynum_blas_complex_float *c, const zynum_blas_int *ldc);
void zherk_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const double *beta, zynum_blas_complex_double *c, const zynum_blas_int *ldc);
void ssyr2k_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const float *alpha, const float *a, const zynum_blas_int *lda, const float *b, const zynum_blas_int *ldb, const float *beta, float *c, const zynum_blas_int *ldc);
void dsyr2k_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const double *alpha, const double *a, const zynum_blas_int *lda, const double *b, const zynum_blas_int *ldb, const double *beta, double *c, const zynum_blas_int *ldc);
void csyr2k_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *b, const zynum_blas_int *ldb, const zynum_blas_complex_float *beta, zynum_blas_complex_float *c, const zynum_blas_int *ldc);
void zsyr2k_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *b, const zynum_blas_int *ldb, const zynum_blas_complex_double *beta, zynum_blas_complex_double *c, const zynum_blas_int *ldc);
void cher2k_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, const zynum_blas_complex_float *b, const zynum_blas_int *ldb, const float *beta, zynum_blas_complex_float *c, const zynum_blas_int *ldc);
void zher2k_(const char *u, const char *t, const zynum_blas_int *n, const zynum_blas_int *k, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, const zynum_blas_complex_double *b, const zynum_blas_int *ldb, const double *beta, zynum_blas_complex_double *c, const zynum_blas_int *ldc);
void strmm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const float *alpha, const float *a, const zynum_blas_int *lda, float *b, const zynum_blas_int *ldb);
void dtrmm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const double *alpha, const double *a, const zynum_blas_int *lda, double *b, const zynum_blas_int *ldb);
void ctrmm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, zynum_blas_complex_float *b, const zynum_blas_int *ldb);
void ztrmm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, zynum_blas_complex_double *b, const zynum_blas_int *ldb);
void strsm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const float *alpha, const float *a, const zynum_blas_int *lda, float *b, const zynum_blas_int *ldb);
void dtrsm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const double *alpha, const double *a, const zynum_blas_int *lda, double *b, const zynum_blas_int *ldb);
void ctrsm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_float *alpha, const zynum_blas_complex_float *a, const zynum_blas_int *lda, zynum_blas_complex_float *b, const zynum_blas_int *ldb);
void ztrsm_(const char *side, const char *u, const char *t, const char *d, const zynum_blas_int *m, const zynum_blas_int *n, const zynum_blas_complex_double *alpha, const zynum_blas_complex_double *a, const zynum_blas_int *lda, zynum_blas_complex_double *b, const zynum_blas_int *ldb);

#ifdef __cplusplus
}
#endif

#endif
