/*
 * Copyright (C) 2026 Zynum contributors
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Generated by tools/generate_compat_headers.zig.
 * Project contact: Kaixiang Huang
 */
#ifndef ZYNUM_BLAS_CBLAS_H
#define ZYNUM_BLAS_CBLAS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef ZYNUM_BLAS_TYPES_DEFINED
#define ZYNUM_BLAS_TYPES_DEFINED
typedef int32_t zynum_blas_int;
typedef struct {
    float real;
    float imag;
} zynum_blas_complex_float;
typedef struct {
    double real;
    double imag;
} zynum_blas_complex_double;
typedef zynum_blas_complex_float zynum_blas_complexF32;
typedef zynum_blas_complex_double zynum_blas_complexF64;
#endif
/* Zynum BLAS currently exports the LP64/32-bit BLAS integer ABI. */
#ifndef CBLAS_INT
#define CBLAS_INT zynum_blas_int
#endif
#ifndef CBLAS_INDEX
#define CBLAS_INDEX zynum_blas_int
#endif
typedef enum CBLAS_ORDER {
    CblasRowMajor = 101,
    CblasColMajor = 102,
} CBLAS_ORDER;

typedef CBLAS_ORDER CBLAS_LAYOUT;

typedef enum CBLAS_TRANSPOSE {
    CblasNoTrans = 111,
    CblasTrans = 112,
    CblasConjTrans = 113,
} CBLAS_TRANSPOSE;

typedef enum CBLAS_UPLO {
    CblasUpper = 121,
    CblasLower = 122,
} CBLAS_UPLO;

typedef enum CBLAS_DIAG {
    CblasNonUnit = 131,
    CblasUnit = 132,
} CBLAS_DIAG;

typedef enum CBLAS_SIDE {
    CblasLeft = 141,
    CblasRight = 142,
} CBLAS_SIDE;

void cblas_sswap(
    CBLAS_INT n,
    float *x,
    CBLAS_INT incx,
    float *y,
    CBLAS_INT incy
);

void cblas_dswap(
    CBLAS_INT n,
    double *x,
    CBLAS_INT incx,
    double *y,
    CBLAS_INT incy
);

void cblas_cswap(
    CBLAS_INT n,
    void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy
);

void cblas_zswap(
    CBLAS_INT n,
    void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy
);

void cblas_scopy(
    CBLAS_INT n,
    const float *x,
    CBLAS_INT incx,
    float *y,
    CBLAS_INT incy
);

void cblas_dcopy(
    CBLAS_INT n,
    const double *x,
    CBLAS_INT incx,
    double *y,
    CBLAS_INT incy
);

void cblas_ccopy(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy
);

void cblas_zcopy(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy
);

void cblas_saxpy(
    CBLAS_INT n,
    float alpha,
    const float *x,
    CBLAS_INT incx,
    float *y,
    CBLAS_INT incy
);

void cblas_daxpy(
    CBLAS_INT n,
    double alpha,
    const double *x,
    CBLAS_INT incx,
    double *y,
    CBLAS_INT incy
);

void cblas_caxpy(
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy
);

void cblas_zaxpy(
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy
);

void cblas_saxpby(
    CBLAS_INT n,
    float alpha,
    const float *x,
    CBLAS_INT incx,
    float beta,
    float *y,
    CBLAS_INT incy
);

void cblas_daxpby(
    CBLAS_INT n,
    double alpha,
    const double *x,
    CBLAS_INT incx,
    double beta,
    double *y,
    CBLAS_INT incy
);

void cblas_caxpby(
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_zaxpby(
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_sscal(
    CBLAS_INT n,
    float alpha,
    float *x,
    CBLAS_INT incx
);

void cblas_dscal(
    CBLAS_INT n,
    double alpha,
    double *x,
    CBLAS_INT incx
);

void cblas_cscal(
    CBLAS_INT n,
    const void *alpha,
    void *x,
    CBLAS_INT incx
);

void cblas_zscal(
    CBLAS_INT n,
    const void *alpha,
    void *x,
    CBLAS_INT incx
);

void cblas_csscal(
    CBLAS_INT n,
    float alpha,
    void *x,
    CBLAS_INT incx
);

void cblas_zdscal(
    CBLAS_INT n,
    double alpha,
    void *x,
    CBLAS_INT incx
);

float cblas_sdot(
    CBLAS_INT n,
    const float *x,
    CBLAS_INT incx,
    const float *y,
    CBLAS_INT incy
);

double cblas_ddot(
    CBLAS_INT n,
    const double *x,
    CBLAS_INT incx,
    const double *y,
    CBLAS_INT incy
);

void cblas_cdotu_sub(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *out
);

void cblas_zdotu_sub(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *out
);

void cblas_cdotc_sub(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *out
);

void cblas_zdotc_sub(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *out
);

float cblas_snrm2(
    CBLAS_INT n,
    const float *x,
    CBLAS_INT incx
);

double cblas_dnrm2(
    CBLAS_INT n,
    const double *x,
    CBLAS_INT incx
);

float cblas_scnrm2(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx
);

double cblas_dznrm2(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx
);

float cblas_sasum(
    CBLAS_INT n,
    const float *x,
    CBLAS_INT incx
);

double cblas_dasum(
    CBLAS_INT n,
    const double *x,
    CBLAS_INT incx
);

float cblas_scasum(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx
);

double cblas_dzasum(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx
);

CBLAS_INDEX cblas_isamax(
    CBLAS_INT n,
    const float *x,
    CBLAS_INT incx
);

CBLAS_INDEX cblas_idamax(
    CBLAS_INT n,
    const double *x,
    CBLAS_INT incx
);

CBLAS_INDEX cblas_icamax(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx
);

CBLAS_INDEX cblas_izamax(
    CBLAS_INT n,
    const void *x,
    CBLAS_INT incx
);

float cblas_sdsdot(
    CBLAS_INT n,
    float sb,
    const float *x,
    CBLAS_INT incx,
    const float *y,
    CBLAS_INT incy
);

double cblas_dsdot(
    CBLAS_INT n,
    const float *x,
    CBLAS_INT incx,
    const float *y,
    CBLAS_INT incy
);

void cblas_srotg(
    float *a,
    float *b,
    float *c,
    float *s
);

void cblas_drotg(
    double *a,
    double *b,
    double *c,
    double *s
);

void cblas_crotg(
    void *a,
    const void *b,
    float *c,
    void *s
);

void cblas_zrotg(
    void *a,
    const void *b,
    double *c,
    void *s
);

void cblas_srot(
    CBLAS_INT n,
    float *x,
    CBLAS_INT incx,
    float *y,
    CBLAS_INT incy,
    float c,
    float s
);

void cblas_drot(
    CBLAS_INT n,
    double *x,
    CBLAS_INT incx,
    double *y,
    CBLAS_INT incy,
    double c,
    double s
);

void cblas_csrot(
    CBLAS_INT n,
    void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy,
    float c,
    float s
);

void cblas_zdrot(
    CBLAS_INT n,
    void *x,
    CBLAS_INT incx,
    void *y,
    CBLAS_INT incy,
    double c,
    double s
);

void cblas_srotm(
    CBLAS_INT n,
    float *x,
    CBLAS_INT incx,
    float *y,
    CBLAS_INT incy,
    const float *param
);

void cblas_drotm(
    CBLAS_INT n,
    double *x,
    CBLAS_INT incx,
    double *y,
    CBLAS_INT incy,
    const double *param
);

void cblas_srotmg(
    float *d1,
    float *d2,
    float *x1,
    float y1,
    float *param
);

void cblas_drotmg(
    double *d1,
    double *d2,
    double *x1,
    double y1,
    double *param
);

void cblas_sgemv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    const float *x,
    CBLAS_INT incx,
    float beta,
    float *y,
    CBLAS_INT incy
);

void cblas_dgemv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    const double *x,
    CBLAS_INT incx,
    double beta,
    double *y,
    CBLAS_INT incy
);

void cblas_cgemv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_zgemv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_sgbmv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT kl,
    CBLAS_INT ku,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    const float *x,
    CBLAS_INT incx,
    float beta,
    float *y,
    CBLAS_INT incy
);

void cblas_dgbmv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT kl,
    CBLAS_INT ku,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    const double *x,
    CBLAS_INT incx,
    double beta,
    double *y,
    CBLAS_INT incy
);

void cblas_cgbmv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT kl,
    CBLAS_INT ku,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_zgbmv(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT kl,
    CBLAS_INT ku,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_ssymv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    const float *x,
    CBLAS_INT incx,
    float beta,
    float *y,
    CBLAS_INT incy
);

void cblas_dsymv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    const double *x,
    CBLAS_INT incx,
    double beta,
    double *y,
    CBLAS_INT incy
);

void cblas_chemv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_zhemv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_ssbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    CBLAS_INT k,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    const float *x,
    CBLAS_INT incx,
    float beta,
    float *y,
    CBLAS_INT incy
);

void cblas_dsbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    CBLAS_INT k,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    const double *x,
    CBLAS_INT incx,
    double beta,
    double *y,
    CBLAS_INT incy
);

void cblas_chbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_zhbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_sspmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const float *ap,
    const float *x,
    CBLAS_INT incx,
    float beta,
    float *y,
    CBLAS_INT incy
);

void cblas_dspmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const double *ap,
    const double *x,
    CBLAS_INT incx,
    double beta,
    double *y,
    CBLAS_INT incy
);

void cblas_chpmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *ap,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_zhpmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *ap,
    const void *x,
    CBLAS_INT incx,
    const void *beta,
    void *y,
    CBLAS_INT incy
);

void cblas_strmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const float *a,
    CBLAS_INT lda,
    float *x,
    CBLAS_INT incx
);

void cblas_dtrmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const double *a,
    CBLAS_INT lda,
    double *x,
    CBLAS_INT incx
);

void cblas_ctrmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_ztrmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_stbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const float *a,
    CBLAS_INT lda,
    float *x,
    CBLAS_INT incx
);

void cblas_dtbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const double *a,
    CBLAS_INT lda,
    double *x,
    CBLAS_INT incx
);

void cblas_ctbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_ztbmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_stpmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const float *ap,
    float *x,
    CBLAS_INT incx
);

void cblas_dtpmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const double *ap,
    double *x,
    CBLAS_INT incx
);

void cblas_ctpmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *ap,
    void *x,
    CBLAS_INT incx
);

void cblas_ztpmv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *ap,
    void *x,
    CBLAS_INT incx
);

void cblas_strsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const float *a,
    CBLAS_INT lda,
    float *x,
    CBLAS_INT incx
);

void cblas_dtrsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const double *a,
    CBLAS_INT lda,
    double *x,
    CBLAS_INT incx
);

void cblas_ctrsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_ztrsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_stbsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const float *a,
    CBLAS_INT lda,
    float *x,
    CBLAS_INT incx
);

void cblas_dtbsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const double *a,
    CBLAS_INT lda,
    double *x,
    CBLAS_INT incx
);

void cblas_ctbsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_ztbsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *a,
    CBLAS_INT lda,
    void *x,
    CBLAS_INT incx
);

void cblas_stpsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const float *ap,
    float *x,
    CBLAS_INT incx
);

void cblas_dtpsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const double *ap,
    double *x,
    CBLAS_INT incx
);

void cblas_ctpsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *ap,
    void *x,
    CBLAS_INT incx
);

void cblas_ztpsv(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_DIAG diag,
    CBLAS_INT n,
    const void *ap,
    void *x,
    CBLAS_INT incx
);

void cblas_sger(
    CBLAS_LAYOUT layout,
    CBLAS_INT m,
    CBLAS_INT n,
    float alpha,
    const float *x,
    CBLAS_INT incx,
    const float *y,
    CBLAS_INT incy,
    float *a,
    CBLAS_INT lda
);

void cblas_dger(
    CBLAS_LAYOUT layout,
    CBLAS_INT m,
    CBLAS_INT n,
    double alpha,
    const double *x,
    CBLAS_INT incx,
    const double *y,
    CBLAS_INT incy,
    double *a,
    CBLAS_INT lda
);

void cblas_cgeru(
    CBLAS_LAYOUT layout,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *a,
    CBLAS_INT lda
);

void cblas_zgeru(
    CBLAS_LAYOUT layout,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *a,
    CBLAS_INT lda
);

void cblas_cgerc(
    CBLAS_LAYOUT layout,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *a,
    CBLAS_INT lda
);

void cblas_zgerc(
    CBLAS_LAYOUT layout,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *a,
    CBLAS_INT lda
);

void cblas_ssyr(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const float *x,
    CBLAS_INT incx,
    float *a,
    CBLAS_INT lda
);

void cblas_dsyr(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const double *x,
    CBLAS_INT incx,
    double *a,
    CBLAS_INT lda
);

void cblas_cher(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const void *x,
    CBLAS_INT incx,
    void *a,
    CBLAS_INT lda
);

void cblas_zher(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const void *x,
    CBLAS_INT incx,
    void *a,
    CBLAS_INT lda
);

void cblas_sspr(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const float *x,
    CBLAS_INT incx,
    float *ap
);

void cblas_dspr(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const double *x,
    CBLAS_INT incx,
    double *ap
);

void cblas_chpr(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const void *x,
    CBLAS_INT incx,
    void *ap
);

void cblas_zhpr(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const void *x,
    CBLAS_INT incx,
    void *ap
);

void cblas_ssyr2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const float *x,
    CBLAS_INT incx,
    const float *y,
    CBLAS_INT incy,
    float *a,
    CBLAS_INT lda
);

void cblas_dsyr2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const double *x,
    CBLAS_INT incx,
    const double *y,
    CBLAS_INT incy,
    double *a,
    CBLAS_INT lda
);

void cblas_cher2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *a,
    CBLAS_INT lda
);

void cblas_zher2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *a,
    CBLAS_INT lda
);

void cblas_sspr2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    float alpha,
    const float *x,
    CBLAS_INT incx,
    const float *y,
    CBLAS_INT incy,
    float *ap
);

void cblas_dspr2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    double alpha,
    const double *x,
    CBLAS_INT incx,
    const double *y,
    CBLAS_INT incy,
    double *ap
);

void cblas_chpr2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *ap
);

void cblas_zhpr2(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_INT n,
    const void *alpha,
    const void *x,
    CBLAS_INT incx,
    const void *y,
    CBLAS_INT incy,
    void *ap
);

void cblas_sgemm(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE transa,
    CBLAS_TRANSPOSE transb,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT k,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    const float *b,
    CBLAS_INT ldb,
    float beta,
    float *c,
    CBLAS_INT ldc
);

void cblas_dgemm(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE transa,
    CBLAS_TRANSPOSE transb,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT k,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    const double *b,
    CBLAS_INT ldb,
    double beta,
    double *c,
    CBLAS_INT ldc
);

void cblas_cgemm(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE transa,
    CBLAS_TRANSPOSE transb,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_zgemm(
    CBLAS_LAYOUT layout,
    CBLAS_TRANSPOSE transa,
    CBLAS_TRANSPOSE transb,
    CBLAS_INT m,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_ssymm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_INT m,
    CBLAS_INT n,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    const float *b,
    CBLAS_INT ldb,
    float beta,
    float *c,
    CBLAS_INT ldc
);

void cblas_dsymm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_INT m,
    CBLAS_INT n,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    const double *b,
    CBLAS_INT ldb,
    double beta,
    double *c,
    CBLAS_INT ldc
);

void cblas_csymm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_zsymm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_chemm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_zhemm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_ssyrk(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    float beta,
    float *c,
    CBLAS_INT ldc
);

void cblas_dsyrk(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    double beta,
    double *c,
    CBLAS_INT ldc
);

void cblas_csyrk(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_zsyrk(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_cherk(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    float alpha,
    const void *a,
    CBLAS_INT lda,
    float beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_zherk(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    double alpha,
    const void *a,
    CBLAS_INT lda,
    double beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_ssyr2k(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    const float *b,
    CBLAS_INT ldb,
    float beta,
    float *c,
    CBLAS_INT ldc
);

void cblas_dsyr2k(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    const double *b,
    CBLAS_INT ldb,
    double beta,
    double *c,
    CBLAS_INT ldc
);

void cblas_csyr2k(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_zsyr2k(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    const void *beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_cher2k(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    float beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_zher2k(
    CBLAS_LAYOUT layout,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE trans,
    CBLAS_INT n,
    CBLAS_INT k,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    const void *b,
    CBLAS_INT ldb,
    double beta,
    void *c,
    CBLAS_INT ldc
);

void cblas_strmm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    float *b,
    CBLAS_INT ldb
);

void cblas_dtrmm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    double *b,
    CBLAS_INT ldb
);

void cblas_ctrmm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    void *b,
    CBLAS_INT ldb
);

void cblas_ztrmm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    void *b,
    CBLAS_INT ldb
);

void cblas_strsm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    float alpha,
    const float *a,
    CBLAS_INT lda,
    float *b,
    CBLAS_INT ldb
);

void cblas_dtrsm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    double alpha,
    const double *a,
    CBLAS_INT lda,
    double *b,
    CBLAS_INT ldb
);

void cblas_ctrsm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    void *b,
    CBLAS_INT ldb
);

void cblas_ztrsm(
    CBLAS_LAYOUT layout,
    CBLAS_SIDE side,
    CBLAS_UPLO uplo,
    CBLAS_TRANSPOSE transa,
    CBLAS_DIAG diag,
    CBLAS_INT m,
    CBLAS_INT n,
    const void *alpha,
    const void *a,
    CBLAS_INT lda,
    void *b,
    CBLAS_INT ldb
);

#ifdef __cplusplus
}
#endif

#endif
