// Copyright (C) 2026 Zynum contributors
// SPDX-License-Identifier: LGPL-3.0-or-later

// Generated by tools/generate_multiversion.py. Do not edit directly.

const options = @import("zynum-build-options");
const protocol = @import("protocol.zig");
const types = @import("../../types.zig");
pub const zynum_level1_sve_candidates = options.level1_sve_candidates;
pub const zynum_level1_fixed_candidates = options.level1_fixed_candidates;
pub const zynum_level2_fixed_candidates = options.level2_fixed_candidates;
pub const zynum_level2_width_candidates = options.level2_width_candidates;
const vector_unary = @import("../dispatch/vector_unary.zig");
const vector_binary = @import("../dispatch/vector_binary.zig");
const matrix_vector = @import("../dispatch/matrix_vector.zig");
const matrix_matrix = @import("../dispatch/matrix_matrix.zig");

fn execute(operation: u32, scalar_id: u32, raw_packet: *anyopaque) callconv(.c) void {
    switch (operation) {
        @intFromEnum(protocol.Operation.vector_unary_scalUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_unary_scalUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.scalUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_unary_scalUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.scalUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_unary_scalUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.vector_unary_scalUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.scalUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.vector_unary_scalUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.scalUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_unary_asumUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_unary_asumUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.asumUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_unary_asumUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.asumUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_unary_asumUnitComplexComponents) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_unary_asumUnitComplexComponents, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.asumUnitComplexComponents, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_unary_asumUnitComplexComponents, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.asumUnitComplexComponents, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_unary_nrm2UnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_unary_nrm2UnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.nrm2UnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_unary_nrm2UnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.nrm2UnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_unary_iamaxUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_unary_iamaxUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.iamaxUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_unary_iamaxUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.iamaxUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_unary_iamaxUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.vector_unary_iamaxUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.iamaxUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.vector_unary_iamaxUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_unary.iamaxUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_fixedCopyBytes) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.vector_binary_fixedCopyBytes, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.fixedCopyBytes, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_copyBytes) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.vector_binary_copyBytes, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.copyBytes, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_copyUnit) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_copyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.copyUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_copyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.copyUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.vector_binary_copyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.copyUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.vector_binary_copyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.copyUnit, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_copyUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_copyUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.copyUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_copyUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.copyUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_swapUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_swapUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.swapUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_swapUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.swapUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_swapUnitRealStreaming) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_swapUnitRealStreaming, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.swapUnitRealStreaming, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_swapUnitRealStreaming, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.swapUnitRealStreaming, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_axpyUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_axpyUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpyUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_axpyUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpyUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_axpyUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.vector_binary_axpyUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpyUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.vector_binary_axpyUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpyUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_axpbyUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_axpbyUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpbyUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_axpbyUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpbyUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_axpbyUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.vector_binary_axpbyUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpbyUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.vector_binary_axpbyUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.axpbyUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_dotUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_dotUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.dotUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_dotUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.dotUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_dotF32AccF64Unit) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.vector_binary_dotF32AccF64Unit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.dotF32AccF64Unit, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_dotUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.vector_binary_dotUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.dotUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.vector_binary_dotUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.dotUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_rotUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_rotUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.rotUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_rotUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.rotUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_rotUnitRealStreaming) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_rotUnitRealStreaming, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.rotUnitRealStreaming, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_rotUnitRealStreaming, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.rotUnitRealStreaming, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.vector_binary_rotmUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.vector_binary_rotmUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.rotmUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.vector_binary_rotmUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, vector_binary.rotmUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvTransUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvTransUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransFullUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvTransFullUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransFullUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvTransFullUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransFullUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransAmxUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvTransAmxUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransAmxUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvTransAmxUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransAmxUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvNoTransRowsUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransRowsUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransRowsUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransRowsUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransRowsUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransRowsUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransRowsUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransRowsUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransRowsUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransRowsUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransFullUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransFullUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransFullUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransTaskUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransTaskUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransTaskUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvNoTransTaskUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransTaskUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransTaskUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvNoTransFullUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransFullUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransFullUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransTaskUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransTaskUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransTaskUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvTransTaskUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransTaskUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransTaskUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransTaskUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransTaskFullUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvTransTaskFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransTaskFullUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvTransTaskFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransTaskFullUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvTransTaskFullUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransTaskFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransTaskFullUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransTaskFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransTaskFullUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransTaskFullUnitComplexC64M512N64) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.matrix_vector_gemvTransTaskFullUnitComplexC64M512N64, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransTaskFullUnitComplexC64M512N64, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransTaskFullUnitComplexC64M256N128) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.matrix_vector_gemvTransTaskFullUnitComplexC64M256N128, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransTaskFullUnitComplexC64M256N128, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvTransFullUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gemvTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransFullUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gemvTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvTransFullUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvTransFullUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransFullUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransFullUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransFullUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvNoTransUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvTransUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvTransUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvTransUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransFullUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransFullUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransFullUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransFullUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransFullUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransPackLenUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransPackLenUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransPackLenUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransPackLenUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransPackLenUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransPackUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransPackUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransPackUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransPackUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransPackUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gemvNoTransPackedRowsUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransPackedRowsUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransPackedRowsUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gemvNoTransPackedRowsUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gemvNoTransPackedRowsUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_supportsGemvNoTransUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_supportsGemvNoTransUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.supportsGemvNoTransUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gerUnitReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_gerUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gerUnitReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_gerUnitReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gerUnitReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_gerUnitComplex) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_gerUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gerUnitComplex, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_gerUnitComplex, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.gerUnitComplex, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_triangularAxpyUnit) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_triangularAxpyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularAxpyUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_triangularAxpyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularAxpyUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_triangularAxpyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularAxpyUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_triangularAxpyUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularAxpyUnit, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_triangularDotUnit) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_triangularDotUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularDotUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_triangularDotUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularDotUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_triangularDotUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularDotUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_triangularDotUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.triangularDotUnit, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_vector_symmetricColumnsUnit) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_vector_symmetricColumnsUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.symmetricColumnsUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_vector_symmetricColumnsUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.symmetricColumnsUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF32)) => {
                const T = types.ComplexF32;
                const packet: *protocol.Packet(.matrix_vector_symmetricColumnsUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.symmetricColumnsUnit, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(types.ComplexF64)) => {
                const T = types.ComplexF64;
                const packet: *protocol.Packet(.matrix_vector_symmetricColumnsUnit, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_vector.symmetricColumnsUnit, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_matrix_candidates) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_matrix_candidates, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.candidates, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_matrix_candidates, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.candidates, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_matrix_noTransReal) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(f32)) => {
                const T = f32;
                const packet: *protocol.Packet(.matrix_matrix_noTransReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.noTransReal, .{T} ++ packet.args);
            },
            @intFromEnum(protocol.scalarId(f64)) => {
                const T = f64;
                const packet: *protocol.Packet(.matrix_matrix_noTransReal, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.noTransReal, .{T} ++ packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_matrix_tryNoTransRealF32Fast) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.matrix_matrix_tryNoTransRealF32Fast, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.tryNoTransRealF32Fast, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_matrix_freeCurrentThreadCaches) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.matrix_matrix_freeCurrentThreadCaches, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.freeCurrentThreadCaches, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_matrix_noTransRealF32) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.matrix_matrix_noTransRealF32, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.noTransRealF32, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        @intFromEnum(protocol.Operation.matrix_matrix_noTransRealF64) => switch (scalar_id) {
            @intFromEnum(protocol.scalarId(void)) => {
                const T = void;
                const packet: *protocol.Packet(.matrix_matrix_noTransRealF64, T) = @ptrCast(@alignCast(raw_packet));
                packet.result = @call(.auto, matrix_matrix.noTransRealF64, packet.args);
            },
            else => @panic("invalid multiversion kernel scalar"),
        },
        else => @panic("invalid multiversion kernel operation"),
    }
}

comptime {
    if (options.dynamic_dispatch) @compileError("kernel tier objects must disable dynamic dispatch");
    @export(&execute, .{ .name = options.kernel_entry, .visibility = .hidden });
}
