#!/usr/bin/env python3
# Copyright (C) 2026 Zynum contributors
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Generate the private, same-build kernel packet protocol and dispatch adapters.

The public dispatch signatures are the source of truth. Run with --check to
verify generated files and adapter lines without changing the repository.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import sys
from dataclasses import dataclass


ROOT = Path(__file__).resolve().parents[1]
MODULES = ("vector_unary", "vector_binary", "matrix_vector", "matrix_matrix")
ADAPTER = re.compile(
    r'\n    if \(comptime @import\("zynum-build-options"\)\.dynamic_dispatch\) '
    r'return @import\("\.\./multiversion/client\.zig"\)\.call\([^\n]*\);'
)
HEADER = """// Copyright (C) 2026 Zynum contributors
// SPDX-License-Identifier: LGPL-3.0-or-later

// Generated by tools/generate_multiversion.py. Do not edit directly.

"""


@dataclass(frozen=True)
class Function:
    module: str
    name: str
    generic: bool
    parameters: tuple[tuple[str, str], ...]
    result: str
    body: int

    @property
    def operation(self) -> str:
        return f"{self.module}_{self.name}"

    @property
    def scalar_types(self) -> tuple[str, ...]:
        if not self.generic:
            return ("void",)
        if self.name in {"copyUnit", "triangularAxpyUnit", "triangularDotUnit", "symmetricColumnsUnit"}:
            return ("f32", "f64", "types.ComplexF32", "types.ComplexF64")
        if "Complex" in self.name and self.name != "asumUnitComplexComponents":
            return ("types.ComplexF32", "types.ComplexF64")
        return ("f32", "f64")


def split_parameters(text: str) -> list[str]:
    parts = []
    start = depth = 0
    for index, char in enumerate(text):
        if char in "([{":
            depth += 1
        elif char in ")]}":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append(text[start:index].strip())
            start = index + 1
    parts.append(text[start:].strip())
    return [part for part in parts if part]


def functions(module: str, source: str) -> list[Function]:
    result = []
    for match in re.finditer(r"\bpub fn (\w+)\(", source):
        name = match.group(1)
        if name == "activeCapability":
            continue
        depth = 1
        end = match.end()
        while depth:
            char = source[end]
            depth += (char == "(") - (char == ")")
            end += 1
        body = source.index("{", end)
        params = split_parameters(source[match.end():end - 1])
        generic = bool(params and params[0] == "comptime T: type")
        if generic:
            params.pop(0)
        if any("comptime" in param or "anytype" in param for param in params):
            raise ValueError(f"Unsupported generic signature: {module}.{name}")
        parsed = tuple(tuple(part.strip() for part in param.split(":", 1)) for param in params)
        if any(len(param) != 2 for param in parsed):
            raise ValueError(f"Unrecognized signature: {module}.{name}")
        result.append(Function(module, name, generic, parsed, source[end:body].strip(), body + 1))
    if not result:
        raise ValueError(f"No dispatch functions found in {module}")
    return result


def formatted(source: str) -> str:
    return subprocess.run(
        ["zig", "fmt", "--stdin"], input=source, text=True,
        capture_output=True, check=True,
    ).stdout


def protocol(functions: list[Function]) -> str:
    signatures = "\n".join(
        repr((f.operation, f.generic, f.parameters, f.result, f.scalar_types)) for f in functions
    )
    digest = hashlib.sha256(signatures.encode()).hexdigest()
    lines = [HEADER, '''//! Private pointer packets shared only by objects from the same build.
//! Zig tuples, optionals and task structs are deliberately not a public C ABI.

const std = @import("std");
const types = @import("../../types.zig");
const scalar = @import("../../core/shared/scalar.zig");
const gemm_task = @import("../shared/matrix_matrix/task.zig");
const catalog = @import("../shared/matrix_matrix/catalog.zig");
const BlasInt = types.BlasInt;
const Task = gemm_task.Task;

pub const Scalar = enum(u32) { none = 0, f32 = 1, f64 = 2, c32 = 3, c64 = 4 };

pub fn scalarId(comptime T: type) Scalar {
    if (T == void) return .none;
    if (T == f32) return .f32;
    if (T == f64) return .f64;
    if (T == types.ComplexF32) return .c32;
    if (T == types.ComplexF64) return .c64;
    @compileError("unsupported multiversion scalar");
}

pub const Operation = enum(u32) {''']
    lines.extend(f"    {f.operation} = {index}," for index, f in enumerate(functions))
    lines += ["};", f'pub const signature_sha256 = "{digest}";',
              "pub fn validScalar(comptime operation: Operation, comptime T: type) bool {", "    return switch (operation) {"]
    lines.extend(f"        .{f.operation} => " + " or ".join(f"T == {t}" for t in f.scalar_types) + "," for f in functions)
    lines += ["    };", "}",
              "pub fn Result(comptime operation: Operation, comptime T: type) type {",
              '    if (!validScalar(operation, T)) @compileError("unsupported scalar for kernel operation");',
              "    return switch (operation) {"]
    lines.extend(f"        .{f.operation} => {f.result}," for f in functions)
    lines += ["    };", "}",
              "pub fn Args(comptime operation: Operation, comptime T: type) type {",
              '    if (!validScalar(operation, T)) @compileError("unsupported scalar for kernel operation");',
              "    return switch (operation) {"]
    lines.extend(f"        .{f.operation} => std.meta.Tuple(&.{{ " + ", ".join(t for _, t in f.parameters) + " })," for f in functions)
    lines += ["    };", "}", '''pub fn Packet(comptime operation: Operation, comptime T: type) type {
    return struct {
        args: Args(operation, T),
        result: Result(operation, T) = undefined,
    };
}

pub const PacketLayout = extern struct {
    size: usize,
    alignment: usize,
    args_offset: usize,
    result_offset: usize,
};

/// Layout diagnostics for same-build host/object integration tests.
pub fn packetLayout(comptime operation: Operation, comptime T: type) PacketLayout {
    const P = Packet(operation, T);
    return .{
        .size = @sizeOf(P),
        .alignment = @alignOf(P),
        .args_offset = @offsetOf(P, "args"),
        .result_offset = @offsetOf(P, "result"),
    };
}
''']
    return formatted("\n".join(lines))


def object_source(functions: list[Function]) -> str:
    lines = [HEADER, 'const options = @import("zynum-build-options");',
             'const protocol = @import("protocol.zig");', 'const types = @import("../../types.zig");']
    lines.extend(f"pub const zynum_{option} = options.{option};" for option in (
        "level1_sve_candidates", "level1_fixed_candidates", "level2_fixed_candidates", "level2_width_candidates",
    ))
    lines.extend(f'const {module} = @import("../dispatch/{module}.zig");' for module in MODULES)
    lines += ['''
fn execute(operation: u32, scalar_id: u32, raw_packet: *anyopaque) callconv(.c) void {
    switch (operation) {''']
    for function in functions:
        lines += [f"        @intFromEnum(protocol.Operation.{function.operation}) => switch (scalar_id) {{"]
        for scalar_type in function.scalar_types:
            arguments = ".{T} ++ packet.args" if function.generic else "packet.args"
            lines += [f"            @intFromEnum(protocol.scalarId({scalar_type})) => {{",
                      f"                const T = {scalar_type};",
                      f"                const packet: *protocol.Packet(.{function.operation}, T) = @ptrCast(@alignCast(raw_packet));",
                      f"                packet.result = @call(.auto, {function.module}.{function.name}, {arguments});",
                      "            },"]
        lines += ['            else => @panic("invalid multiversion kernel scalar"),', "        },"]
    lines += ['        else => @panic("invalid multiversion kernel operation"),', "    }", "}", '''
comptime {
    if (options.dynamic_dispatch) @compileError("kernel tier objects must disable dynamic dispatch");
    @export(&execute, .{ .name = options.kernel_entry, .visibility = .hidden });
}
''']
    return formatted("\n".join(lines))


def outputs() -> dict[Path, str]:
    result = {}
    all_functions = []
    for module in MODULES:
        path = ROOT / f"src/blas/kernels/dispatch/{module}.zig"
        source = ADAPTER.sub("", path.read_text())
        parsed = functions(module, source)
        all_functions.extend(parsed)
        for function in reversed(parsed):
            arguments = ", ".join(name for name, _ in function.parameters)
            scalar_type = "T" if function.generic else "void"
            adapter = (f'\n    if (comptime @import("zynum-build-options").dynamic_dispatch) '
                       f'return @import("../multiversion/client.zig").call(.{function.operation}, '
                       f'{scalar_type}, .{{ {arguments} }});')
            source = source[:function.body] + adapter + source[function.body:]
        result[path] = formatted(source)
    directory = ROOT / "src/blas/kernels/multiversion"
    result[directory / "protocol.zig"] = protocol(all_functions)
    result[directory / "object.zig"] = object_source(all_functions)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mismatches = []
    for path, expected in outputs().items():
        if not path.exists() or path.read_text() != expected:
            if args.check:
                mismatches.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected)
    if mismatches:
        print("Stale multiversion outputs: " + ", ".join(mismatches), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
